### ISSUE TITLE
Failed to Install GeoPandas with Git/Pip/Conda

### ISSUE THREAD

**Issue by fillipefeitosa** [conda-forge/geopandas-feedstock#37]
As discussed on [GeoPandas Repository](https://github.com/geopandas/geopandas/issues/712), I could not install it using any of the methods described on the tutorial.
**Using Rasbian, on Raspberry Pi 3, with miniconda installed**. My Objetive is to use GeoPandas on Jupyter Notebooks

Here is my output:
```
(jupyter) pi@raspberrypi:~ $ conda install -c conda-forge geopandas
Fetching package metadata .......

PackageNotFoundError: Package missing in current linux-armv7l channels: 
  - geopandas

Close matches found; did you mean one of these?

    geopandas: pandas, django-pandas
```
Any Help would be appreciated.

**Comment by ocefpaf** [comment]
> As discussed on GeoPandas Repository

Like I mention there conda-forge does not build packages for Raspberry Pi.
Unfortunately, even if we make `geopandas` `noarch`, which I believe it is possible with the current version but not the next one due to the cython parts, you would still hit the same wall with `shapely` and `fiona` (`geopandas` dependencies), and ultimately `gdal`.

@jjhelmus had a conda channel for raspeberry pi but I'm not sure if he packages `geopandas` there.

**Comment by jjhelmus** [comment]
[Berryconda](https://github.com/jjhelmus/berryconda) and the [`rpi` channel](https://anaconda.org/rpi) is a collection of conda packages for the Raspberry Pi.  These do not include `geopandas` but some of the dependency are there and could be used as a starting point if someone wanted to build out the geopandas stack.

**Comment by fillipefeitosa** [comment]
Thanks for all your responses.
